### ISSUE TITLE
StreamListener `debug` param deprecated

### ISSUE THREAD

**Issue by nachouve** [mberk/betfairutil#9]
There is an small error using function `prices_file_to_data_frame`.

> ~/.local/lib/python3.8/site-packages/betfairutil/__init__.py in prices_file_to_csv_file(path_to_prices_file, path_to_csv_file, **kwargs)
>     715     path_to_prices_file: str, path_to_csv_file: str, **kwargs
>     716 ) -> None:
> --> 717     prices_file_to_data_frame(path_to_prices_file, **kwargs).to_csv(
>     718         path_to_csv_file, index=False
>     719     )
> 
> ~/.local/lib/python3.8/site-packages/betfairutil/__init__.py in prices_file_to_data_frame(path_to_prices_file, should_output_runner_names, should_format_publish_time, max_depth)
>     752     stream = trading.streaming.create_historical_generator_stream(
>     753         file_path=path_to_prices_file,
> --> 754         listener=StreamListener(
>     755             max_latency=None, lightweight=True, debug=False, update_clk=False
>     756         ),
> 
> TypeError: __init__() got an unexpected keyword argument 'debug'

Checking the [historic commit at bflw](https://github.com/liampauling/betfair/commit/b081a51b1d3afb734f370eaa6b4878f40f2cacbb#) I see that:

> `debug` param to be deprecated from v2.15.0 and handled explicitly

**Comment by mberk** [comment]
This was fixed in version 0.1.1: https://github.com/mberk/betfairutil/pull/8/commits/68fe5229efda865f844d86016678013bbed0c7ba

Please update your copy of the package and try again

**Comment by nachouve** [comment]
Yes, you are right! 
Sorry for the ticket.
